name: Test JavaScript examples

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: javascript


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Test `invokeModel`
        run: node invokeModel/invokeModel.js