name: "Test C# examples"

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: csharp


jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Test `invokeModel`
        run: node invokeModel/invokeModel.js

      - name: Test `converse`
        run: node converse/converse.js

      - name: Test `converseStream`
        run: node converseStream/converseStream.js