name: Test JavaScript examples
on:
  pull_request:
    branches: ["main"]


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Workspace
        uses: 0xTheProDev/setup-js@v1.2

      - name: Get versions
        run: |
          node --version
          npm --version
          npx --version